#!/bin/sh

TITLE="Please wait..."
COMMAND=""

# Parse options
while [ $# -gt 0 ]; do
    case "$1" in
        --title)
            TITLE="$2"
            shift 2
            ;;
        --*) # Ignore all other -- options and their value if present
            shift
            if [ $# -gt 0 ] && [ "${1#--}" = "$1" ]; then
                shift
            fi
            ;;
        *)  # First non-option: start of the command
            COMMAND="$*"
            break
            ;;
    esac
done

if [ -z "$COMMAND" ]; then
    echo "Usage: $0 [--title title] command [args...]"
    exit 1
fi

# Start the target command in the background
sh -c "$COMMAND" &
CMD_PID=$!

wait $CMD_PID
exit_code=$?

exit $exit_code